import React from 'react'
import NextDocument, { Html, Head, Main, NextScript } from 'next/document'
import { getCssText, reset, darkTheme, globalCss } from '@Theme'

const getCssAndReset = () => {
  const css = getCssText()
  reset()
  return css
}

export default class Document extends NextDocument {
  render() {
    return (
      <Html lang="en">
        <Head>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <style
            id="stitches"
            dangerouslySetInnerHTML={{ __html: getCssAndReset() }}
          />
        </Head>
        <body id="root" className={darkTheme}>
          <Main />
          <NextScript />
        </body>
      </Html>
    )
  }
}
