import React from 'react'
import NextDocument, { Html, Head, Main, NextScript } from 'next/document'
import { getCssText, reset, darkTheme, globalCss } from '@Theme'

const getCssAndReset = () => {
  const css = getCssText()
  reset()
  return css
}

export default class Document extends NextDocument {
  render() {
    return (
      <Html lang="en">
        <Head>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <style
            id="stitches"
            dangerouslySetInnerHTML={{ __html: getCssAndReset() }}
          />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link
            rel="preconnect"
            href="https://fonts.gstatic.com"
            crossOrigin="true"
          />
          <link
            href="https://fonts.googleapis.com/css2?family=Big+Shoulders+Display:wght@500;700;900&family=Inter:wght@100;300;400;500;600;700;900&family=Poppins:wght@300;400;500;600;700;900&family=Roboto+Mono&display=swap"
            rel="stylesheet"
          />
        </Head>
        <body id="root" className={darkTheme}>
          <Main />
          <NextScript />
        </body>
      </Html>
    )
  }
}
