import {
  gray,
  mauve,
  slate,
  sage,
  olive,
  sand,
  tomato,
  red,
  crimson,
  pink,
  plum,
  purple,
  violet,
  indigo,
  blue,
  sky,
  mint,
  cyan,
  teal,
  green,
  grass,
  lime,
  yellow,
  amber,
  orange,
  brown,
  bronze,
  gold,
  grayA,
  mauveA,
  slateA,
  sageA,
  oliveA,
  sandA,
  tomatoA,
  redA,
  crimsonA,
  pinkA,
  plumA,
  purpleA,
  violetA,
  indigoA,
  blueA,
  skyA,
  mintA,
  cyanA,
  tealA,
  greenA,
  grassA,
  limeA,
  yellowA,
  amberA,
  orangeA,
  brownA,
  bronzeA,
  goldA,
  whiteA,
  blackA,
  grayDark,
  mauveDark,
  slateDark,
  sageDark,
  oliveDark,
  sandDark,
  tomatoDark,
  redDark,
  crimsonDark,
  pinkDark,
  plumDark,
  purpleDark,
  violetDark,
  indigoDark,
  blueDark,
  skyDark,
  mintDark,
  cyanDark,
  tealDark,
  greenDark,
  grassDark,
  limeDark,
  yellowDark,
  amberDark,
  orangeDark,
  brownDark,
  bronzeDark,
  goldDark,
  grayDarkA,
  mauveDarkA,
  slateDarkA,
  sageDarkA,
  oliveDarkA,
  sandDarkA,
  tomatoDarkA,
  redDarkA,
  crimsonDarkA,
  pinkDarkA,
  plumDarkA,
  purpleDarkA,
  violetDarkA,
  indigoDarkA,
  blueDarkA,
  skyDarkA,
  mintDarkA,
  cyanDarkA,
  tealDarkA,
  greenDarkA,
  grassDarkA,
  limeDarkA,
  yellowDarkA,
  amberDarkA,
  orangeDarkA,
  brownDarkA,
  bronzeDarkA,
  goldDarkA,
} from '@radix-ui/colors'

export const light = {
  ...gray,
  ...mauve,
  ...slate,
  ...sage,
  ...olive,
  ...sand,
  ...tomato,
  ...red,
  ...crimson,
  ...pink,
  ...plum,
  ...purple,
  ...violet,
  ...indigo,
  ...blue,
  ...sky,
  ...mint,
  ...cyan,
  ...teal,
  ...green,
  ...grass,
  ...lime,
  ...yellow,
  ...amber,
  ...orange,
  ...brown,
  ...bronze,
  ...gold,

  ...grayA,
  ...mauveA,
  ...slateA,
  ...sageA,
  ...oliveA,
  ...sandA,
  ...tomatoA,
  ...redA,
  ...crimsonA,
  ...pinkA,
  ...plumA,
  ...purpleA,
  ...violetA,
  ...indigoA,
  ...blueA,
  ...skyA,
  ...mintA,
  ...cyanA,
  ...tealA,
  ...greenA,
  ...grassA,
  ...limeA,
  ...yellowA,
  ...amberA,
  ...orangeA,
  ...brownA,
  ...bronzeA,
  ...goldA,

  ...whiteA,
  ...blackA,

  colorScheme: 'white',
  invertColorScheme: 'black',
  colorSchemeA1: whiteA.whiteA1,
  colorSchemeA2: whiteA.whiteA2,
  colorSchemeA3: whiteA.whiteA3,
  colorSchemeA4: whiteA.whiteA4,
  colorSchemeA5: whiteA.whiteA5,
  colorSchemeA6: whiteA.whiteA6,
  colorSchemeA7: whiteA.whiteA7,
  colorSchemeA8: whiteA.whiteA8,
  colorSchemeA9: whiteA.whiteA9,
  colorSchemeA10: whiteA.whiteA10,
  colorSchemeA11: whiteA.whiteA11,
  colorSchemeA12: whiteA.whiteA12,
  invertColorSchemeA1: blackA.blackA1,
  invertColorSchemeA2: blackA.blackA2,
  invertColorSchemeA3: blackA.blackA3,
  invertColorSchemeA4: blackA.blackA4,
  invertColorSchemeA5: blackA.blackA5,
  invertColorSchemeA6: blackA.blackA6,
  invertColorSchemeA7: blackA.blackA7,
  invertColorSchemeA8: blackA.blackA8,
  invertColorSchemeA9: blackA.blackA9,
  invertColorSchemeA10: blackA.blackA10,
  invertColorSchemeA11: blackA.blackA11,
  invertColorSchemeA12: blackA.blackA12,
  grayscale1: slate.slate1,
  grayscale2: slate.slate2,
  grayscale3: slate.slate3,
  grayscale4: slate.slate4,
  grayscale5: slate.slate5,
  grayscale6: slate.slate6,
  grayscale7: slate.slate7,
  grayscale8: slate.slate8,
  grayscale9: slate.slate9,
  grayscale10: slate.slate10,
  grayscale11: slate.slate11,
  grayscale12: slate.slate12,
  // Semantic colors
  hiContrast: '$slate12',
  hiContrastA: '$slateA12',
  // loContrast: '$slate1',
  loContrast: 'white',
  loContrastA: '$slateA1',
  canvas: 'hsl(0 0% 93%)',
  panel: 'white',
  transparentPanel: 'hsl(0 0% 0% / 97%)',
  shadowLight: 'hsl(206 22% 7% / 35%)',
  shadowDark: 'hsl(206 22% 7% / 20%)',
}

export const dark = {
  ...grayDark,
  ...mauveDark,
  ...slateDark,
  ...sageDark,
  ...oliveDark,
  ...sandDark,
  ...tomatoDark,
  ...redDark,
  ...crimsonDark,
  ...pinkDark,
  ...plumDark,
  ...purpleDark,
  ...violetDark,
  ...indigoDark,
  ...blueDark,
  ...skyDark,
  ...mintDark,
  ...cyanDark,
  ...tealDark,
  ...greenDark,
  ...grassDark,
  ...limeDark,
  ...yellowDark,
  ...amberDark,
  ...orangeDark,
  ...brownDark,
  ...bronzeDark,
  ...goldDark,

  ...grayDarkA,
  ...mauveDarkA,
  ...slateDarkA,
  ...sageDarkA,
  ...oliveDarkA,
  ...sandDarkA,
  ...tomatoDarkA,
  ...redDarkA,
  ...crimsonDarkA,
  ...pinkDarkA,
  ...plumDarkA,
  ...purpleDarkA,
  ...violetDarkA,
  ...indigoDarkA,
  ...blueDarkA,
  ...skyDarkA,
  ...mintDarkA,
  ...cyanDarkA,
  ...tealDarkA,
  ...greenDarkA,
  ...grassDarkA,
  ...limeDarkA,
  ...yellowDarkA,
  ...amberDarkA,
  ...orangeDarkA,
  ...brownDarkA,
  ...bronzeDarkA,
  ...goldDarkA,

  colorScheme: 'black',
  invertColorScheme: 'white',
  colorSchemeA1: blackA.blackA1,
  colorSchemeA2: blackA.blackA2,
  colorSchemeA3: blackA.blackA3,
  colorSchemeA4: blackA.blackA4,
  colorSchemeA5: blackA.blackA5,
  colorSchemeA6: blackA.blackA6,
  colorSchemeA7: blackA.blackA7,
  colorSchemeA8: blackA.blackA8,
  colorSchemeA9: blackA.blackA9,
  colorSchemeA10: blackA.blackA10,
  colorSchemeA11: blackA.blackA11,
  colorSchemeA12: blackA.blackA12,
  invertColorSchemeA1: whiteA.whiteA1,
  invertColorSchemeA2: whiteA.whiteA2,
  invertColorSchemeA3: whiteA.whiteA3,
  invertColorSchemeA4: whiteA.whiteA4,
  invertColorSchemeA5: whiteA.whiteA5,
  invertColorSchemeA6: whiteA.whiteA6,
  invertColorSchemeA7: whiteA.whiteA7,
  invertColorSchemeA8: whiteA.whiteA8,
  invertColorSchemeA9: whiteA.whiteA9,
  invertColorSchemeA10: whiteA.whiteA10,
  invertColorSchemeA11: whiteA.whiteA11,
  invertColorSchemeA12: whiteA.whiteA12,
  // Semantic colors
  hiContrast: 'white',
  hiContrastA: '$slateA12',
  loContrast: '$slate1',
  loContrastA: '$slateA1',
  // loContrast: 'black',
  canvas: 'hsl(0 0% 15%)',
  panel: '$slate3',
  transparentPanel: 'hsl(0 100% 100% / 97%)',
  shadowLight: 'hsl(206 22% 7% / 35%)',
  shadowDark: 'hsl(206 22% 7% / 20%)',
}
