name: CICD Branch Dev

# Controls when the workflow will run
on:
    push:
        branches: [dev]
    pull_request:
        branches: [dev]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    build:
        runs-on: ubuntu-latest
        env:
            CI: false
            PUBLIC_API_ROOT: ${{ secrets.PUBLIC_API_ROOT_DEV }}
        steps:
            - uses: actions/checkout@v2
            - name: Setup node.js env
              uses: actions/setup-node@master
              with:
                  node-version: '16'
                  cache: 'yarn'
            - run: npm ci
            - run: npm run export

            - name: Upload artifact for deployment job
              uses: actions/upload-artifact@v2
              with:
                  name: out
                  path: ./out

    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: 'Development'
        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v2
              with:
                  name: out
                  path: ./out

            - name: Deploy to server
              uses: appleboy/scp-action@master
              with:
                  username: ${{ secrets.HOST_USERNAME }}
                  host: ${{ secrets.HOST }}
                  key: ${{ secrets.SSH_KEY }}
                  port: ${{ secrets.PORT }}
                  source: './out'
                  target: '/var/www/mavens.upanastudio.com'
                  use_insecure_cipher: true

            - name: Send telegram notification
              if: always()
              uses: haishanh/actions-telegram-notification@v1
              with:
                  notification-token: ${{ secrets.NOTIFICATION_TOKEN }}
                  job-status: ${{ job.status }}

              # delete-artifact
            - uses: geekyeggo/delete-artifact@v1
              if: always()
              with:
                  name: out
